# Generated by Django 6.0.4 on 2026-04-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yuk qabuli',
                'verbose_name_plural': 'Yuk qabullari',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('KIRIM', 'Kirim'), ('CHIQIM', 'Chiqim'), ('TUZATISH', 'Tuzatish')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('moved_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='toifa.product')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar tarixi',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='toifa.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ombor.warehousereceipt')),
            ],
            options={
                'verbose_name': 'Qabul elementi',
                'verbose_name_plural': 'Qabul elementlari',
            },
        ),
    ]
