# Generated by Django 6.0.4 on 2026-04-22 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='qr_payload',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehousereceipt',
            name='receipt_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
