# Generated by Django 6.0.4 on 2026-04-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('DOKON', "Do'kon"), ('SHAXSIY', 'Shaxsiy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hisob',
                'verbose_name_plural': 'Hisoblar',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('KIRIM', 'Kirim'), ('CHIQIM', 'Chiqim')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kassa.cashaccount')),
            ],
            options={
                'verbose_name': 'Kassa tranzaksiya',
                'verbose_name_plural': 'Kassa tranzaksiyalari',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transfers', to='kassa.cashaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transfers', to='kassa.cashaccount')),
            ],
            options={
                'verbose_name': "O'tkazma",
                'verbose_name_plural': "O'tkazmalar",
                'ordering': ['-occurred_at'],
            },
        ),
    ]
