# Generated by Django 6.0.4 on 2026-04-22 06:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('language', models.CharField(default='uz', max_length=10)),
                ('notification_phone', models.CharField(blank=True, max_length=30)),
                ('low_stock_alert_limit', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Do'kon profili",
                'verbose_name_plural': "Do'kon profillari",
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('file_type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eksport log',
                'verbose_name_plural': 'Eksport loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xavfsizlik sozlamasi',
                'verbose_name_plural': 'Xavfsizlik sozlamalari',
            },
        ),
    ]
